1) Categorical NBC on Adult dataset
2) K-Fold Cross Validation and it's types :
   (a) K-Fold Cross Validation using sklearn
   (b) K-Fold without using SKlearn (Using index splitting)
   (c) K-Fold without using SKlearn (Using np.array_split())
   (d) Stratified K-Fold
   

In [1]:
# after removing data row as index row and changing column names
import pandas as pd
import numpy as np
df=pd.read_csv('C:\\Users\\soham\\Downloads\\adult.data',names=['age','workclass','fnlwgt','education','education-num','marital-status','occupation','relationship','race','sex','capital-gain','capital-loss','hours-per-week','native-country','income'],header=None)
df  

age          workclass  fnlwgt      education  education-num  \
0       39          State-gov   77516      Bachelors             13   
1       50   Self-emp-not-inc   83311      Bachelors             13   
2       38            Private  215646        HS-grad              9   
3       53            Private  234721           11th              7   
4       28            Private  338409      Bachelors             13   
5       37            Private  284582        Masters             14   
6       49            Private  160187            9th              5   
7       52   Self-emp-not-inc  209642        HS-grad              9   
8       31            Private   45781        Masters             14   
9       42            Private  159449      Bachelors             13   
10      37            Private  280464   Some-college             10   
11      30          State-gov  141297      Bachelors             13   
12      23            Private  122272      Bachelors             13   
13      32            Private  205019     Assoc-acdm             12   
14      40            Private  121772      Assoc-voc             11   
15      34            Private  245487        7th-8th              4   
16      25   Self-emp-not-inc  176756        HS-grad              9   
17      32            Private  186824        HS-grad              9   
18      38            Private   28887           11th              7   
19      43   Self-emp-not-inc  292175        Masters             14   
20      40            Private  193524      Doctorate             16   
21      54            Private  302146        HS-grad              9   
22      35        Federal-gov   76845            9th              5   
23      43            Private  117037           11th              7   
24      59            Private  109015        HS-grad              9   
25      56          Local-gov  216851      Bachelors             13   
26      19            Private  168294        HS-grad              9   
27      54                  ?  180211   Some-college             10   
28      39            Private  367260        HS-grad              9   
29      49            Private  193366        HS-grad              9   
...    ...                ...     ...            ...            ...   
32531   30                  ?   33811      Bachelors             13   
32532   34            Private  204461      Doctorate             16   
32533   54            Private  337992      Bachelors             13   
32534   37            Private  179137   Some-college             10   
32535   22            Private  325033           12th              8   
32536   34            Private  160216      Bachelors             13   
32537   30            Private  345898        HS-grad              9   
32538   38            Private  139180      Bachelors             13   
32539   71                  ?  287372      Doctorate             16   
32540   45          State-gov  252208        HS-grad              9   
32541   41                  ?  202822        HS-grad              9   
32542   72                  ?  129912        HS-grad              9   
32543   45          Local-gov  119199     Assoc-acdm             12   
32544   31            Private  199655        Masters             14   
32545   39          Local-gov  111499     Assoc-acdm             12   
32546   37            Private  198216     Assoc-acdm             12   
32547   43            Private  260761        HS-grad              9   
32548   65   Self-emp-not-inc   99359    Prof-school             15   
32549   43          State-gov  255835   Some-college             10   
32550   43   Self-emp-not-inc   27242   Some-college             10   
32551   32            Private   34066           10th              6   
32552   43            Private   84661      Assoc-voc             11   
32553   32            Private  116138        Masters             14   
32554   53            Private  321865        Masters             14   
32555   22            Private  

In [2]:
#replacing "?" by np.nan
df=df.replace(' ?',np.nan)
#replace missing values by mean,mode
for i in df.columns:
    if (type(df[i].dropna().tolist()[0])==str): #we are checking type of first value of each column after dropping NA's from it.
        df[i]=df[i].fillna(df[i].mode()[0])   #So, no problem even if first value of column turns out to be missing
    elif (type(df[i].dropna().tolist()[0])==float):  #we are checking type of first available element of that column using dropna 
        df[i]=df[i].fillna(df[i].mean())
df

age          workclass  fnlwgt      education  education-num  \
0       39          State-gov   77516      Bachelors             13   
1       50   Self-emp-not-inc   83311      Bachelors             13   
2       38            Private  215646        HS-grad              9   
3       53            Private  234721           11th              7   
4       28            Private  338409      Bachelors             13   
5       37            Private  284582        Masters             14   
6       49            Private  160187            9th              5   
7       52   Self-emp-not-inc  209642        HS-grad              9   
8       31            Private   45781        Masters             14   
9       42            Private  159449      Bachelors             13   
10      37            Private  280464   Some-college             10   
11      30          State-gov  141297      Bachelors             13   
12      23            Private  122272      Bachelors             13   
13      32            Private  205019     Assoc-acdm             12   
14      40            Private  121772      Assoc-voc             11   
15      34            Private  245487        7th-8th              4   
16      25   Self-emp-not-inc  176756        HS-grad              9   
17      32            Private  186824        HS-grad              9   
18      38            Private   28887           11th              7   
19      43   Self-emp-not-inc  292175        Masters             14   
20      40            Private  193524      Doctorate             16   
21      54            Private  302146        HS-grad              9   
22      35        Federal-gov   76845            9th              5   
23      43            Private  117037           11th              7   
24      59            Private  109015        HS-grad              9   
25      56          Local-gov  216851      Bachelors             13   
26      19            Private  168294        HS-grad              9   
27      54            Private  180211   Some-college             10   
28      39            Private  367260        HS-grad              9   
29      49            Private  193366        HS-grad              9   
...    ...                ...     ...            ...            ...   
32531   30            Private   33811      Bachelors             13   
32532   34            Private  204461      Doctorate             16   
32533   54            Private  337992      Bachelors             13   
32534   37            Private  179137   Some-college             10   
32535   22            Private  325033           12th              8   
32536   34            Private  160216      Bachelors             13   
32537   30            Private  345898        HS-grad              9   
32538   38            Private  139180      Bachelors             13   
32539   71            Private  287372      Doctorate             16   
32540   45          State-gov  252208        HS-grad              9   
32541   41            Private  202822        HS-grad              9   
32542   72            Private  129912        HS-grad              9   
32543   45          Local-gov  119199     Assoc-acdm             12   
32544   31            Private  199655        Masters             14   
32545   39          Local-gov  111499     Assoc-acdm             12   
32546   37            Private  198216     Assoc-acdm             12   
32547   43            Private  260761        HS-grad              9   
32548   65   Self-emp-not-inc   99359    Prof-school             15   
32549   43          State-gov  255835   Some-college             10   
32550   43   Self-emp-not-inc   27242   Some-college             10   
32551   32            Private   34066           10th              6   
32552   43            Private   84661      Assoc-voc             11   
32553   32            Private  116138        Masters             14   
32554   53            Private  321865        Masters             14   
32555   22            Private  

In [3]:
#creating a dataframe with only string type columns
dfobj=pd.DataFrame()
for i in df.columns:
    if (type(df[i].tolist()[0])==str):
        dfobj[i]=df[i].tolist()
dfobj

workclass      education          marital-status  \
0              State-gov      Bachelors           Never-married   
1       Self-emp-not-inc      Bachelors      Married-civ-spouse   
2                Private        HS-grad                Divorced   
3                Private           11th      Married-civ-spouse   
4                Private      Bachelors      Married-civ-spouse   
5                Private        Masters      Married-civ-spouse   
6                Private            9th   Married-spouse-absent   
7       Self-emp-not-inc        HS-grad      Married-civ-spouse   
8                Private        Masters           Never-married   
9                Private      Bachelors      Married-civ-spouse   
10               Private   Some-college      Married-civ-spouse   
11             State-gov      Bachelors      Married-civ-spouse   
12               Private      Bachelors           Never-married   
13               Private     Assoc-acdm           Never-married   
14               Private      Assoc-voc      Married-civ-spouse   
15               Private        7th-8th      Married-civ-spouse   
16      Self-emp-not-inc        HS-grad           Never-married   
17               Private        HS-grad           Never-married   
18               Private           11th      Married-civ-spouse   
19      Self-emp-not-inc        Masters                Divorced   
20               Private      Doctorate      Married-civ-spouse   
21               Private        HS-grad               Separated   
22           Federal-gov            9th      Married-civ-spouse   
23               Private           11th      Married-civ-spouse   
24               Private        HS-grad                Divorced   
25             Local-gov      Bachelors      Married-civ-spouse   
26               Private        HS-grad           Never-married   
27               Private   Some-college      Married-civ-spouse   
28               Private        HS-grad                Divorced   
29               Private        HS-grad      Married-civ-spouse   
...                  ...            ...                     ...   
32531            Private      Bachelors           Never-married   
32532            Private      Doctorate      Married-civ-spouse   
32533            Private      Bachelors      Married-civ-spouse   
32534            Private   Some-college                Divorced   
32535            Private           12th           Never-married   
32536            Private      Bachelors           Never-married   
32537            Private        HS-grad           Never-married   
32538            Private      Bachelors                Divorced   
32539            Private      Doctorate      Married-civ-spouse   
32540          State-gov        HS-grad               Separated   
32541            Private        HS-grad               Separated   
32542            Private        HS-grad      Married-civ-spouse   
32543          Local-gov     Assoc-acdm                Divorced   
32544            Private        Masters                Divorced   
32545          Local-gov     Assoc-acdm      Married-civ-spouse   
32546            Private     Assoc-acdm                Divorced   
32547            Private        HS-grad      Married-civ-spouse   
32548   Self-emp-not-inc    Prof-school           Never-married   
32549          State-gov   Some-college                Divorced   
32550   Self-emp-not-inc   Some-college      Married-civ-spouse   
32551            Private           10th      Married-civ-spouse   
32552            Private      Assoc-voc      Married-civ-spouse   
32553            Private        Masters           Never-married   
32554            Private        Masters      Married-civ-spouse   
32555            Private   Some-college           Never-married   
32556            Private     Assoc-acdm      Married-civ-spouse   
32557            Private        HS-grad      Married-civ-spouse   
32558            Private        HS-grad                 Widowe

In [4]:
#performing train-test-split on our dataframe
# X consists of only categorical columns, y consists of output column("income")
import numpy as np
from sklearn.model_selection import train_test_split
X, y = dfobj.iloc[:,0:7],dfobj.iloc[:,[-1]]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=5)

In [6]:
#to obtain a dictionary of the class priors of output column
def getClassPriors(opcol):
    opcol=list(opcol)
    CP={i:opcol.count(i)/len(opcol) for i in np.unique(opcol)}
    return(CP)

getClassPriors(y_train['income'])

{' >50K': 0.24126886626886626, ' <=50K': 0.7587311337311338}

In [7]:
# calculating the conditional probability of each category for each output value
def getcondProbs(inp_traindf,op_traindf,opcol):
    Conpro={j:{k:  len(inp_traindf[i][(inp_traindf[i]==j) & (op_traindf[opcol]==k)])     /     len(op_traindf[opcol][(op_traindf[opcol]==k)])   for k in np.unique(op_traindf[opcol]) }  for i in inp_traindf.columns.values  for j in np.unique(inp_traindf[i]) }               
    return Conpro 

getcondProbs(X_train,y_train,'income')       

{' State-gov': {' >50K': 0.0452809601745772, ' <=50K': 0.03851269299716648},
 ' Local-gov': {' >50K': 0.0734679032551373, ' <=50K': 0.06025559474932053},
 ' Without-pay': {' >50K': 0.0, ' <=50K': 0.000693922396345342},
 ' Federal-gov': {' >50K': 0.05091834879068922,
  ' <=50K': 0.023940322673914303},
 ' Never-worked': {' >50K': 0.0, ' <=50K': 0.000346961198172671},
 ' Self-emp-inc': {' >50K': 0.07710492816875796,
  ' <=50K': 0.020065922627652805},
 ' Private': {' >50K': 0.662302236770322, ' <=50K': 0.7815879257503036},
 ' Self-emp-not-inc': {' >50K': 0.09092562284051646,
  ' <=50K': 0.07459665760712426},
 ' Some-college': {' >50K': 0.1789416257501364, ' <=50K': 0.23940322673914297},
 ' Assoc-voc': {' >50K': 0.04582651391162029, ' <=50K': 0.0405366333198404},
 ' Masters': {' >50K': 0.12293144208037826, ' <=50K': 0.03116868096917828},
 ' 7th-8th': {' >50K': 0.005455537370430988, ' <=50K': 0.023188573411206847},
 ' Assoc-acdm': {' >50K': 0.03364248045099109, ' <=50K': 0.0327300063609553},

In [8]:
# predicting the output of a single row 
# for each possible output value, (multiplying together the condprob of each element of input row)
# and then declaring the greater value of multiplication as our predection

def predictone(inp,condprobs,classpriors):
    outprob={}
    for i in classpriors.keys():
        l=[condprobs[inp[j]][i] for j in inp.index]
        outprob[i]=np.prod(l)*classpriors[i]
    #print(outprob)   
        
    return max(outprob, key=outprob.get)

predictone(X_test.iloc[0,0:7],  getcondProbs(X_train,y_train,'income'),  getClassPriors(y_train['income'])) 

' <=50K'

In [9]:
def predictall(X_test,y_test,condprobs,classpriors):
    y_pred=X_test.apply(lambda i:predictone(i,condprobs,classpriors), axis=1 )
    return y_pred

predictall(X_test,y_test,getcondProbs(X_train,y_train,'income') ,getClassPriors(y_train['income']))   

32264     <=50K
28024     <=50K
9347      <=50K
10427     <=50K
4810      <=50K
11139     <=50K
20926     <=50K
24150      >50K
15504     <=50K
9407      <=50K
8963      <=50K
12107      >50K
157       <=50K
21946      >50K
14238      >50K
2684       >50K
24774     <=50K
31521     <=50K
20148      >50K
1783       >50K
25516     <=50K
15029     <=50K
13136     <=50K
25779     <=50K
26879      >50K
10207     <=50K
11367     <=50K
23913      >50K
30387     <=50K
9346      <=50K
          ...  
25053      >50K
26478     <=50K
23368      >50K
26636     <=50K
22505     <=50K
6995      <=50K
59        <=50K
11276     <=50K
27296     <=50K
1431      <=50K
13144     <=50K
23339      >50K
3490      <=50K
8074       >50K
20341     <=50K
24870     <=50K
14760      >50K
17919     <=50K
30833     <=50K
4343       >50K
5220       >50K
12702     <=50K
18032     <=50K
25331      >50K
17952     <=50K
7577       >50K
17553     <=50K
24131      >50K
13961      >50K
3335      <=50K
Length: 9769, dtype: obj

In [10]:
def accuracy(actlist,predlist):
    acc=(sum([a==b for (a,b) in zip(predlist,actlist)])/len(predlist))*100
    print('Accuracy of Algorithm is : ',acc,'%')
    return acc # used return bcoz we want to use it ahead in K-fold Cross Validation
    
accuracy(y_test['income'].tolist(),  predictall(X_test,y_test,getcondProbs(X_train,y_train,'income') ,getClassPriors(y_train['income'])) )

Accuracy of Algorithm is :  78.9128877060088 %


78.9128877060088

"""K-Fold Cross Validation"""

1) K-Fold Cross Validation using sklearn

In [14]:
import numpy as np
from sklearn.model_selection import KFold
X = dfobj.iloc[:,:7]
y = dfobj.iloc[:,[-1]]
kf = KFold(n_splits=5)
#kf = KFold(n_splits=5, shuffle=True, random_state=5)
# by default shuffle is false, but we can use (shuffle=True) with a random state to split data after shuffling
kf.get_n_splits(X)

print(kf)

KFold(n_splits=5, random_state=None, shuffle=False)


In [15]:
acc=[]
for train_index, test_index in kf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    acc.append(accuracy(y_test['income'].tolist(),  predictall(X_test,y_test,getcondProbs(X_train,y_train,'income') ,getClassPriors(y_train['income'])) ))
    
print(acc)

accavg=np.sum(acc)/len(acc)
accavg

TRAIN: [ 6513  6514  6515 ... 32558 32559 32560] TEST: [   0    1    2 ... 6510 6511 6512]
Accuracy of Algorithm is :  79.149393520651 %
TRAIN: [    0     1     2 ... 32558 32559 32560] TEST: [ 6513  6514  6515 ... 13022 13023 13024]
Accuracy of Algorithm is :  78.71621621621621 %
TRAIN: [    0     1     2 ... 32558 32559 32560] TEST: [13025 13026 13027 ... 19534 19535 19536]
Accuracy of Algorithm is :  78.65479115479116 %
TRAIN: [    0     1     2 ... 32558 32559 32560] TEST: [19537 19538 19539 ... 26046 26047 26048]
Accuracy of Algorithm is :  79.26904176904176 %
TRAIN: [    0     1     2 ... 26046 26047 26048] TEST: [26049 26050 26051 ... 32558 32559 32560]
Accuracy of Algorithm is :  78.53194103194103 %
[79.149393520651, 78.71621621621621, 78.65479115479116, 79.26904176904176, 78.53194103194103]


78.86427673852823

2) K-Fold without using SKlearn (Using index splitting)

In [18]:
#correct way of splitting list into a number of parts (inspired from source of numpy.array_split())

import math 
def chunks(lst, n):
    l=[]
    for i in range(0, (len(lst)%n)*((len(lst)//n)+1) , (len(lst)//n)+1):  
        l.append(lst[i:i + ((len(lst)//n)+1)])
    for i in range((len(lst)%n)*((len(lst)//n)+1) , len(lst), len(lst)//n):  
        l.append(lst[i:i + len(lst)//n])
        
    return l

In [19]:
a=[1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10,1,2,3]
chunks(a,9)
# chunks() divides the list 'a' into 9 parts by maintaining utmost equality

[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9],
 [10, 1, 2],
 [3, 4, 5],
 [6, 7],
 [8, 9],
 [10, 1],
 [2, 3]]

In [20]:
import numpy as np

n_splits=5
l=dfobj.index.tolist()
np.random.seed(5) #setting a random state for shuffle
np.random.shuffle(l)#shuffles data to make it random


In [23]:
acc=[]
data_index=chunks(l,n_splits)
for i in chunks(l,n_splits):
    test_index=i
    data_index.remove(i)
    train_index=[inner for outer in data_index for inner in outer ]
    data_index=chunks(l,n_splits)
    print("TRAIN:")
    print(train_index)
    print('TEST:')
    print(test_index)
    train_X, test_X = dfobj.iloc[train_index,0:7], dfobj.iloc[test_index,0:7]
    train_y, test_y = dfobj.iloc[train_index,[-1]],dfobj.iloc[test_index,[-1]]
    acc.append(  accuracy(  test_y['income'].tolist(),  predictall(test_X,test_y,getcondProbs(train_X,train_y,'income') ,getClassPriors(train_y['income']) ) )  )
    
print(acc)
accavg=np.sum(acc)/len(acc)
accavg
    

TRAIN:
[21425, 28707, 4455, 2231, 18864, 4655, 12726, 13363, 4033, 19220, 6854, 26040, 23335, 8743, 6603, 29806, 9403, 9538, 15433, 6200, 4127, 21892, 26099, 30555, 15514, 27580, 5139, 5435, 3766, 28854, 14026, 27205, 15460, 20031, 15607, 27963, 23085, 8160, 24636, 8488, 967, 16241, 4601, 12805, 22497, 16788, 21793, 6986, 4153, 17762, 24450, 23140, 5291, 23262, 26584, 14320, 28370, 32530, 22525, 27188, 10425, 5748, 8353, 22460, 19278, 6822, 18676, 29125, 24944, 7133, 32027, 2452, 27814, 11161, 10907, 12850, 27095, 4711, 24446, 24206, 2665, 8905, 31389, 26198, 18258, 3056, 29779, 19052, 6102, 6518, 28375, 5513, 23089, 14997, 17742, 6911, 8368, 12494, 11764, 14142, 20673, 2451, 27349, 16215, 18921, 22369, 4245, 4607, 8341, 3951, 10684, 27283, 18512, 27169, 2246, 19201, 10839, 7735, 8848, 8329, 23393, 26872, 27024, 17978, 15596, 9064, 3620, 15202, 2420, 22729, 31773, 424, 20236, 25988, 25410, 29835, 18352, 24679, 8852, 9747, 24258, 19686, 23771, 21386, 705, 22940, 10118, 31562, 10334, 261

Accuracy of Algorithm is :  79.149393520651 %
TRAIN:
[32264, 28024, 9347, 10427, 4810, 11139, 20926, 24150, 15504, 9407, 8963, 12107, 157, 21946, 14238, 2684, 24774, 31521, 20148, 1783, 25516, 15029, 13136, 25779, 26879, 10207, 11367, 23913, 30387, 9346, 6494, 18515, 3405, 6798, 21046, 18841, 19392, 28773, 16687, 6842, 8023, 26966, 7003, 23299, 28982, 20691, 22632, 17508, 4031, 29237, 11562, 21869, 31322, 19194, 28151, 7190, 28986, 3742, 8323, 29045, 21218, 17682, 4042, 5070, 31700, 20579, 19577, 6191, 20615, 31438, 1537, 17735, 23315, 15429, 32391, 20671, 29703, 16742, 1662, 4642, 25274, 2432, 8658, 16050, 26044, 5942, 15317, 25293, 17203, 7606, 24204, 4252, 9567, 31481, 28642, 2647, 21299, 6343, 13937, 12944, 12273, 28086, 4530, 15549, 14791, 21100, 917, 12935, 20731, 16458, 15622, 1683, 9035, 295, 8208, 8611, 3181, 5162, 11014, 31751, 23026, 7219, 8295, 29580, 12775, 15552, 753, 19728, 25977, 13251, 21951, 29406, 18156, 5605, 2860, 6943, 26036, 12624, 2126, 23835, 16722, 10952, 3246

Accuracy of Algorithm is :  78.05589680589681 %
TRAIN:
[32264, 28024, 9347, 10427, 4810, 11139, 20926, 24150, 15504, 9407, 8963, 12107, 157, 21946, 14238, 2684, 24774, 31521, 20148, 1783, 25516, 15029, 13136, 25779, 26879, 10207, 11367, 23913, 30387, 9346, 6494, 18515, 3405, 6798, 21046, 18841, 19392, 28773, 16687, 6842, 8023, 26966, 7003, 23299, 28982, 20691, 22632, 17508, 4031, 29237, 11562, 21869, 31322, 19194, 28151, 7190, 28986, 3742, 8323, 29045, 21218, 17682, 4042, 5070, 31700, 20579, 19577, 6191, 20615, 31438, 1537, 17735, 23315, 15429, 32391, 20671, 29703, 16742, 1662, 4642, 25274, 2432, 8658, 16050, 26044, 5942, 15317, 25293, 17203, 7606, 24204, 4252, 9567, 31481, 28642, 2647, 21299, 6343, 13937, 12944, 12273, 28086, 4530, 15549, 14791, 21100, 917, 12935, 20731, 16458, 15622, 1683, 9035, 295, 8208, 8611, 3181, 5162, 11014, 31751, 23026, 7219, 8295, 29580, 12775, 15552, 753, 19728, 25977, 13251, 21951, 29406, 18156, 5605, 2860, 6943, 26036, 12624, 2126, 23835, 16722, 10952, 32

Accuracy of Algorithm is :  78.20945945945947 %
TRAIN:
[32264, 28024, 9347, 10427, 4810, 11139, 20926, 24150, 15504, 9407, 8963, 12107, 157, 21946, 14238, 2684, 24774, 31521, 20148, 1783, 25516, 15029, 13136, 25779, 26879, 10207, 11367, 23913, 30387, 9346, 6494, 18515, 3405, 6798, 21046, 18841, 19392, 28773, 16687, 6842, 8023, 26966, 7003, 23299, 28982, 20691, 22632, 17508, 4031, 29237, 11562, 21869, 31322, 19194, 28151, 7190, 28986, 3742, 8323, 29045, 21218, 17682, 4042, 5070, 31700, 20579, 19577, 6191, 20615, 31438, 1537, 17735, 23315, 15429, 32391, 20671, 29703, 16742, 1662, 4642, 25274, 2432, 8658, 16050, 26044, 5942, 15317, 25293, 17203, 7606, 24204, 4252, 9567, 31481, 28642, 2647, 21299, 6343, 13937, 12944, 12273, 28086, 4530, 15549, 14791, 21100, 917, 12935, 20731, 16458, 15622, 1683, 9035, 295, 8208, 8611, 3181, 5162, 11014, 31751, 23026, 7219, 8295, 29580, 12775, 15552, 753, 19728, 25977, 13251, 21951, 29406, 18156, 5605, 2860, 6943, 26036, 12624, 2126, 23835, 16722, 10952, 32

Accuracy of Algorithm is :  78.05589680589681 %
TRAIN:
[32264, 28024, 9347, 10427, 4810, 11139, 20926, 24150, 15504, 9407, 8963, 12107, 157, 21946, 14238, 2684, 24774, 31521, 20148, 1783, 25516, 15029, 13136, 25779, 26879, 10207, 11367, 23913, 30387, 9346, 6494, 18515, 3405, 6798, 21046, 18841, 19392, 28773, 16687, 6842, 8023, 26966, 7003, 23299, 28982, 20691, 22632, 17508, 4031, 29237, 11562, 21869, 31322, 19194, 28151, 7190, 28986, 3742, 8323, 29045, 21218, 17682, 4042, 5070, 31700, 20579, 19577, 6191, 20615, 31438, 1537, 17735, 23315, 15429, 32391, 20671, 29703, 16742, 1662, 4642, 25274, 2432, 8658, 16050, 26044, 5942, 15317, 25293, 17203, 7606, 24204, 4252, 9567, 31481, 28642, 2647, 21299, 6343, 13937, 12944, 12273, 28086, 4530, 15549, 14791, 21100, 917, 12935, 20731, 16458, 15622, 1683, 9035, 295, 8208, 8611, 3181, 5162, 11014, 31751, 23026, 7219, 8295, 29580, 12775, 15552, 753, 19728, 25977, 13251, 21951, 29406, 18156, 5605, 2860, 6943, 26036, 12624, 2126, 23835, 16722, 10952, 32

Accuracy of Algorithm is :  80.54361179361179 %
[79.149393520651, 78.05589680589681, 78.20945945945947, 78.05589680589681, 80.54361179361179]


78.80285167710318

3) K-Fold without using SKlearn (Using np.array_split())

 #For an array of length l that should be split
 into n sections, it returns l % n sub-arrays of size l//n + 1
 and the rest of size l//n.(same concept as used above, but here using ready-made function np.array_split())

In [29]:
k = 5
folds = np.array_split(dfobj, k)
folds

[              workclass      education          marital-status  \
 0             State-gov      Bachelors           Never-married   
 1      Self-emp-not-inc      Bachelors      Married-civ-spouse   
 2               Private        HS-grad                Divorced   
 3               Private           11th      Married-civ-spouse   
 4               Private      Bachelors      Married-civ-spouse   
 5               Private        Masters      Married-civ-spouse   
 6               Private            9th   Married-spouse-absent   
 7      Self-emp-not-inc        HS-grad      Married-civ-spouse   
 8               Private        Masters           Never-married   
 9               Private      Bachelors      Married-civ-spouse   
 10              Private   Some-college      Married-civ-spouse   
 11            State-gov      Bachelors      Married-civ-spouse   
 12              Private      Bachelors           Never-married   
 13              Private     Assoc-acdm           Never-marrie

In [30]:
a=[1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10,1,2,3]
b=np.array_split(a,9)
b

[array([1, 2, 3]),
 array([4, 5, 6]),
 array([7, 8, 9]),
 array([10,  1,  2]),
 array([3, 4, 5]),
 array([6, 7]),
 array([8, 9]),
 array([10,  1]),
 array([2, 3])]

In [31]:
acc=[]
for i in range(k):
    train = folds.copy()  #you wanna work on a copy of your array
    test = folds[i]
    del train[i]
    train = pd.concat(train, sort=False)
    print("TRAIN:", train.index, "TEST:", test.index)
    train_X, test_X = train.iloc[:,0:7], test.iloc[:,0:7]
    train_y, test_y = train.iloc[:,[-1]], test.iloc[:,[-1]]
    acc.append(accuracy(  test_y['income'].tolist(),  predictall(test_X,test_y,getcondProbs(train_X,train_y,'income') ,getClassPriors(train_y['income']) ) ))
    
print(acc)  
accavg=np.sum(acc)/len(acc)
accavg

TRAIN: RangeIndex(start=6513, stop=32561, step=1) TEST: RangeIndex(start=0, stop=6513, step=1)
Accuracy of Algorithm is :  79.149393520651 %
TRAIN: Int64Index([    0,     1,     2,     3,     4,     5,     6,     7,     8,
                9,
            ...
            32551, 32552, 32553, 32554, 32555, 32556, 32557, 32558, 32559,
            32560],
           dtype='int64', length=26049) TEST: RangeIndex(start=6513, stop=13025, step=1)
Accuracy of Algorithm is :  78.71621621621621 %
TRAIN: Int64Index([    0,     1,     2,     3,     4,     5,     6,     7,     8,
                9,
            ...
            32551, 32552, 32553, 32554, 32555, 32556, 32557, 32558, 32559,
            32560],
           dtype='int64', length=26049) TEST: RangeIndex(start=13025, stop=19537, step=1)
Accuracy of Algorithm is :  78.65479115479116 %
TRAIN: Int64Index([    0,     1,     2,     3,     4,     5,     6,     7,     8,
                9,
            ...
            32551, 32552, 32553, 32554, 325

78.86427673852823

4) Stratified K-Fold

In [32]:
import numpy as np
from sklearn.model_selection import StratifiedKFold
X = dfobj.iloc[:,:7]
y = dfobj.iloc[:,[-1]]
skf = StratifiedKFold(n_splits=5)
skf.get_n_splits(X, y)

print(skf)

StratifiedKFold(n_splits=5, random_state=None, shuffle=False)


In [33]:
acc=[]
for train_index, test_index in skf.split(X, y):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    acc.append(accuracy(  test_y['income'].tolist(),  predictall(test_X,test_y,getcondProbs(train_X,train_y,'income') ,getClassPriors(train_y['income']) ) ))
    
print(acc)

accavg=np.sum(acc)/len(acc)
accavg

TRAIN: [ 6499  6500  6512 ... 32558 32559 32560] TEST: [   0    1    2 ... 6514 6515 6516]
Accuracy of Algorithm is :  78.53194103194103 %
TRAIN: [    0     1     2 ... 32558 32559 32560] TEST: [ 6499  6500  6512 ... 13121 13123 13125]
Accuracy of Algorithm is :  78.53194103194103 %
TRAIN: [    0     1     2 ... 32558 32559 32560] TEST: [12997 12999 13000 ... 19727 19729 19733]
Accuracy of Algorithm is :  78.53194103194103 %
TRAIN: [    0     1     2 ... 32558 32559 32560] TEST: [19482 19484 19485 ... 26161 26168 26170]
Accuracy of Algorithm is :  78.53194103194103 %
TRAIN: [    0     1     2 ... 26161 26168 26170] TEST: [26005 26006 26007 ... 32558 32559 32560]
Accuracy of Algorithm is :  78.53194103194103 %
[78.53194103194103, 78.53194103194103, 78.53194103194103, 78.53194103194103, 78.53194103194103]


78.53194103194103